linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - revive
    - gosimple
    - unconvert
    - unused

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gofmt
      text: "File is not `gofmt`-ed"

output:
  formats:
    - format: colored-line-number
    - format: json

  print-issued-lines: true
  print-linter-name: true
