linters:
  enable-all: true
  disable:
    - exhaustruct
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - gosec
    - ireturn
    - maligned
    - nestif # remove
    - nlreturn
    - nonamedreturns # fix maybe?
    - scopelint
    - testpackage # TODO: remove this
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  godox:
    keywords:
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-around that should be removed before merging
  lll:
    line-length: 130
