version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupword
    - embeddedstructfieldcheck
    - errcheck
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gosec
    - ireturn
    - mnd
    - modernize
    - nestif
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    lll:
      line-length: 130
formatters:
  enable:
    - gofmt
