version: "2"

run:
  go: "1.26"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - unconvert
    - unused
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
