linters:
  enable-all: true
  disable:
    - depguard
    - dupword
    - exhaustruct
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gomnd
    - gosec
    - ireturn
    - maligned
    - nestif # remove
    - nlreturn
    - nonamedreturns # fix maybe?
    - paralleltest
    - scopelint
    - testpackage # TODO: remove this
    - varnamelen
    - wrapcheck
    - wsl
    - varcheck
    - deadcode
    - nosnakecase
    - golint
    - structcheck
    - ifshort
    - interfacer
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
linters-settings:
  godox:
    keywords:
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-around that should be removed before merging
  lll:
    line-length: 130
