coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto
        informational: true
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        paths:
          - "pkg"
        if_not_found: success
        if_ci_failed: error

ignore:
  - "pkg/generated/**"
  - "**/zz_generated.*.go"
  - "**/fake_api.go"
