coverage:
  status:
    patch:
      default:
        target: 0% # FIXME: This should be auto
        threshold: 100% # FIXME: this should be as small as possible
        base: auto
    project:
      default:
        target: auto
        threshold: 100%
        base: auto
        paths:
          - "pkg"
        if_not_found: success
        if_ci_failed: error
