kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeserial
subjects:
- kind: ServiceAccount
  name: kubeserial
  namespace: kubeserial
roleRef:
  kind: ClusterRole
  name: kubeserial
  apiGroup: rbac.authorization.k8s.io
