apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeserial.fullname" . }}
  labels:
    {{- include "kubeserial.labels" . | nindent 4 }}
data:
{{- $currentScope := .}}
{{- range $path, $_ :=  .Files.Glob  "specs/**.yaml" }}
    {{- with $currentScope}}
  {{ $path | base }}: {{ tpl (.Files.Get $path) . | toYaml | nindent 4 }}
    {{- end }}
{{ end }}
