apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeserial.fullname" . }}
  labels:
    {{- include "kubeserial.labels" . | nindent 4 }}
data:
  monitor-spec.yaml: {{ tpl (.Files.Get "specs/device-monitor.yaml" ) . | toYaml | nindent 4 }}
