apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeserial.fullname" . }}
  labels:
    {{- include "kubeserial.labels" . | nindent 4 }}
data:
  monitor-daemonset-spec.yaml: {{ tpl (.Files.Get "specs/monitor-daemonset.yaml" ) . | toYaml | nindent 4 }}
  monitor-configmap-spec.yaml: {{ tpl (.Files.Get "specs/monitor-configmap.yaml" ) . | toYaml | nindent 4 }}
