apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    test: app
  name: test-monitor
  namespace: test-ns
spec:
  selector:
    matchLabels: 
      test: app
  template:
    metadata:
      labels:
        test: app
      name: test-monitor
    spec:
      containers:
      - image: sample-image:dev
        imagePullPolicy: Always
        name: udev-monitor
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev
          name: host-dev
        - mountPath: /etc/udev/rules.d/98-devices.rules
          name: config
          subPath: 98-devices.rules
      - args:
        - -c
        - ./go/bin/device-monitor
        command:
        - /bin/sh
        env:
        - name: OPERATOR_NAMESPACE
          value: testing-ns
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: sample-image:dev
        imagePullPolicy: Always
        name: device-monitor
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: host-dev
      serviceAccountName: testing
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - configMap:
          defaultMode: 420
          items:
          - key: 98-devices.rules
            path: 98-devices.rules
          name: kubeserial-monitor
        name: config
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
