apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeserial.fullname" . }}
  labels:
    {{- include "kubeserial.labels" . | nindent 4 }}
data:
  monitorLabels: |
    {{- include "kubeserial.monitorLabels" . | nindent 4 }}
  monitorSelectorLabels: |
    {{- include "kubeserial.monitorSelectorLabels" . | nindent 4 }}
