{{- range .Values.kubeserial.devices }}
apiVersion: app.kubeserial.com/v1alpha1
kind: SerialDevice
metadata:
  name: {{ .name }}
  labels:
    {{- include "kubeserial.labels" $ | nindent 4 }}
spec:
    idProduct: {{ .idProduct | quote }}
    idVendor: {{ .idVendor | quote }}
    name: {{ .name | quote }}
    manager: {{ .manager | quote }}
---
{{- end }}
