apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeserial.injectorFullname" . }}
  labels:
    {{- include "kubeserial.injectorLabels" . | nindent 4 }}
data:
  sidecarconfig.yaml: |
    containers:
    - name: device-injector
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "sleep infinity" ]
    volume:
      name: devices
      emptyDir:
        medium: Memory
    volumeMount:
      mountPath: "/dev/devices"
      name: devices
