apiVersion: app.kubeserial.com/v1alpha1
kind: KubeSerial
metadata:
  name: {{ include "kubeserial.fullname" . }}
  labels:
    {{- include "kubeserial.labels" . | nindent 4 }}
spec:
  serialDevices: {{ .Values.kubeserial.serialDevices | toYaml | nindent 4 }}
{{- if .Values.ingress }}
  ingress: {{ .Values.ingress | toYaml | nindent 4 }}
{{- end }}
