apiVersion: v1
kind: Service
metadata:
  labels: {{ include "kubeserial.managerLabels" . | nindent 4 }}
  name: {{ include "kubeserial.managerFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector: {{ include "kubeserial.managerSelectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
