apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: {{ include "kubeserial.monitorLabels" . | nindent 8 }}
  name: {{ include "kubeserial.monitorFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: {{ include "kubeserial.monitorSelectorLabels" . | nindent 10 }}
  template:
    metadata:
      labels: {{ include "kubeserial.monitorLabels" . | nindent 12 }}
      name: {{ include "kubeserial.monitorFullname" . }}
    spec:
      containers:
      - image: {{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag }}
        imagePullPolicy: {{ .Values.monitor.image.pullPolicy }}
        name: udev-monitor
        resources: {{ .Values.monitor.resources | toYaml | nindent 14 }}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /dev
            name: host-dev
          - mountPath: /etc/udev/rules.d/98-devices.rules
            name: config
            subPath: 98-devices.rules
      - args:
          - -c
          - ./go/bin/device-monitor
        command:
          - /bin/sh
        env:
          - name: OPERATOR_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        image: {{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag }}
        imagePullPolicy: {{ .Values.monitor.image.pullPolicy }}
        name: device-monitor
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /dev
            name: host-dev
      serviceAccountName: {{ include "kubeserial.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /dev
            type: ""
            name: host-dev
          name: host-dev
        - configMap:
            defaultMode: 420
            items:
            - key: 98-devices.rules
              path: 98-devices.rules
              name: kubeserial-monitor
            name: {{ include "kubeserial.fullname" . }}-monitor
          name: config
  updateStrategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
      type: RollingUpdate
