apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ include "kubeserial.monitorLabels" . | nindent 4 }}
  name: {{ include "kubeserial.monitorFullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  98-devices.rules: TODO
