replicaCount: 1

kubeserial:
  serialDevices: []

certManagerIssuer:
  name:
  kind: Issuer

webhook:
  image:
    repository: ghcr.io/janekbaraniewski/kubeserial-injector-webhook
    pullPolicy: IfNotPresent
    tag: "APP_VERSION"

monitor:
  image:
    repository: ghcr.io/janekbaraniewski/kubeserial-device-monitor
    pullPolicy: IfNotPresent
    tag: "APP_VERSION"
  resources: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - antarctica-east1
          - antarctica-west1

image:
  repository: ghcr.io/janekbaraniewski/kubeserial
  pullPolicy: IfNotPresent
  tag: "APP_VERSION"

monitoring:
  prometheusMonitors:
    enabled: false

ingress:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
