name: Test Docs

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'docs/**'

jobs:
  mdbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        curl -sSL https://github.com/badboy/mdbook-mermaid/releases/download/v0.10.0/mdbook-mermaid-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        curl -sSL https://github.com/badboy/mdbook-open-on-gh/releases/download/2.0.2/mdbook-open-on-gh-2.0.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        curl -sSL https://github.com/badboy/mdbook-toc/releases/download/0.8.0/mdbook-toc-0.8.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: mdbook test
      run: |
        cd docs
        mdbook test .
    - name: mdbook build
      run: |
        cd docs
        mdbook build .
    - name: upload docs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docs-book
        path: docs/book
