name: GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        make docs-deps
    - name: Deploy GitHub Pages
      run: |
        cd docs
        mdbook build
        git worktree add gh-pages gh-pages
        git config user.name "CI automatic build"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force
