name: GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        curl -sSL https://github.com/badboy/mdbook-mermaid/releases/download/v0.10.0/mdbook-mermaid-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        curl -sSL https://github.com/badboy/mdbook-open-on-gh/releases/download/2.0.2/mdbook-open-on-gh-2.0.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        curl -sSL https://github.com/badboy/mdbook-toc/releases/download/0.8.0/mdbook-toc-0.8.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Deploy GitHub Pages
      run: |
        cd docs
        mdbook build
        git worktree add gh-pages gh-pages
        git config user.name "CI automatic build"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force
