name: Helm

on:
  push:
    branches: [ master ]
    tags:
    - 'v*.*.*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Helm lint
        run: helm lint ./deploy/chart/kubeserial/
