---
name: "pre-release"

on:
  push:
    branches:
      - "master"

permissions:
  contents: read

concurrency:
  group: pre-release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: "Test"
        run: make test
      # - name: "Test code gen"
      #   run: make check-generated
      - name: "Build"
        run: make all
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          prerelease: true
          name: "Dev build"
          files: |
            LICENSE
            build/_output/bin/kubeserial
            build/_output/bin/device-monitor
            build/_output/bin/injector-webhook
            coverage.txt
