name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set target platforms
        run: echo "PLATFORMS=$(cat TARGET_PLATFORMS)" >> $GITHUB_ENV
      - name: Build
        run: make kubeserial-docker-all

  docker-device-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set target platforms
        run: echo "PLATFORMS=$(cat TARGET_PLATFORMS)" >> $GITHUB_ENV
      - name: Build
        run: make device-monitor-docker-all

  docker-injector-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set target platforms
        run: echo "PLATFORMS=$(cat TARGET_PLATFORMS)" >> $GITHUB_ENV
      - name: Build
        run: make injector-webhook-docker-all

  helm-chart:
    runs-on: ubuntu-latest
    needs: docker-controller
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Use release version in chart
        run: VERSION=${RELEASE_VERSION} make update-kubeserial-chart-version

      - name: Push chart to charts repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'charts/kubeserial'
          destination-github-username: 'janekbaraniewski'
          destination-repository-name: 'charts'
          user-email: dev@baraniewski.com
          target-branch: main
          target-directory: 'charts/kubeserial'

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
