name: Release CRDs

on:
  push:
    tags:
    - '^crds-[0-9]+.[0-9]+.[0-9]+$'

jobs:
  helm-chart:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/crds-}" >> $GITHUB_ENV

      - name: Use release version in chart
        run: VERSION=${RELEASE_VERSION} make update-kubeserial-crds-chart-version

      - name: Push chart to charts repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'deploy/chart/kubeserial-crds'
          destination-github-username: 'janekbaraniewski'
          destination-repository-name: 'charts'
          user-email: dev@baraniewski.com
          target-branch: main
          target-directory: 'charts/kubeserial-crds'

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
