name: Test

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'charts/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  docker-controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Set target platforms
        run: echo "PLATFORMS=$(cat TARGET_PLATFORMS)" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: false
          tags: janekbaraniewski/kubeserial:${{ env.RELEASE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-device-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Set target platforms
        run: echo "PLATFORMS=$(cat TARGET_PLATFORMS)" >> $GITHUB_ENV
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: false
          tags: janekbaraniewski/kubeserial-device-monitor:${{ env.RELEASE_VERSION }}
          file: Dockerfile.monitor
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-injector-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Set target platforms
        run: echo "PLATFORMS=$(cat TARGET_PLATFORMS)" >> $GITHUB_ENV

      - name: Log into Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: make injector-webhook-docker-all
        env:
          DOCKERBUILD_ACTION: --load

  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check codegen
        run: make check-generated

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Test
      run: make test
    - name: Upload coverage
      uses: codecov/codecov-action@v1
